---
title: "Seminar Report 2"
output:
  html_document:
    df_print: paged
---

####Name: Zoe Sawyer
####Seminar Speaker: Dr. Ali D. Guler, Assistant Professor of Biology, Univerisity of Virginia
####Date and Time: 11/07/2018, 1:00 PM
####Seminar Title: "Food, time, and dopamine: How rewarding snacks hijack your brain"

## Summary

### Circadian Circuitry

####The seminar began with an explanation and investigation of the circadian rhythm and how it relates to the physiological functions happening in the brain. The circadian rhythm is a result of the evolution of the body to take advantage of day and night. Animals have different behaviors in the day versus night, and this is affected by the endocrine system. In general, the circadian circuitry is governed by the part of the brain called the suprachiasmatic nucleus (SCN). The SCN receives a lot of information from the eyes. This allows the body to adjust the circadian rhythm continuously, which is necessary because due to the rotation of the earth the days are not exactly 24 hours. Therefore, the body's "clock" adjusts itself a little bit each day by synching with the light you see. The information of our eyes seeing light is collected by the SCN, and the SCN neurons fire a lot during the day when you are seeing light but decrease their activity at night.


####More specifically, the intrinsically photosensitive retinal ganglion cells (ipRGCs) in the eye are responsible for communicating the amount of light one sees to the SCN neurons in the brain. These cells were studied in mice, which are nocturnal and often run on their wheel in their cage during the night. For normal mice, if you move them to a different time zone they quickly adjust to the shifted daylight cycle. But, if you remove, or ablate, the ipRGCs in the eyes and do the same experiment, the mice are unable to adjust to the shifted daylight cycle. These ipRGC ablated mice are visually perfect and can see completely normally, but they are unable to detect differences in the amount of light they see from day to night. So, the ipRGC ablated mice do not have normal visual signaling to the SCN and therefore cannot adjust their circadian rhythm.

### Dopamine and the SCN

####The SCN also receives non-photic information regarding environmental events. Dopamine neurons respond to salient events and signal the SCN in the brain that something important is happening so the brain can focus its attention accordingly. However, not all stimuli are created equal" the brain focuses more on rewarding events. For example, a study on the elevation of dopamine and its effects on increasing SCN activity was conducted in mice. To elevate dopamine, capsaicin, a very spicy substance found in hot peppers, was given to mice that were knockouts for the pain gene sensor for capsaicin. This was done as to not induce pain in the mice. Capsaicin is a natural substance that induces dopamine release. The mice were injected with the capsaicin and started running around, similar to the effects of cocaine. Then, images of the SCN were taken. Mice that were given capsaicin experienced an increase in the expression of the C-Fos gene, leading to the conclusion that there is possibly a direct input of dopamine neurons into the SCN.

####It is known that the dopamine receptor DRD1 is expressed in the SCN, creating the presence of SCN-DRD1 neurons, which are the SCN neurons that express the DRD1 receptor. A study showed that the activation of DRD1-SCN neurons were found to mimic the phase response to light. In this study, mice were in an indoor light controlled environment where a light was shone on them during normal daylight hours, and during normal nighttime hours the light was turned off to create a dark environment. Doing this did not affect their normal daytime or night time normal behaviors. Next, the timing of the light was changed and the light was shone on the mice during their normal nighttime hours. This shifted the daylight cycle of the mice.

####To study this further, a drug was administered to mice that activated the DNR1-SCN neurons.  Two different groups of mice were studied: one normal or wild-type, and one in which the mice did not express DNR1 receptors. For the group of mice that expressed the DNR1 receptor, when the DNR-SCN-activating drug was administered at night when the animals were active, this caused a shift in their activity. These two studies go to show that the DNR neurons in the SCN are an important part of the physiology that regulates the circadian rhythm. The C-Fos gene expression activity was also examined in this study and showed that there was a linear relationship between increased DNR1-SCN activity and the amount of delay that occurs before the mouse successfully adjusts its circadian rhythm. Therefore, the amount of activity of the SCN is related to the ability of an animal to shift its biological clock and adjust to a different daytime/nighttime cycle.

### Homeostasis and Obesity

####Next, the focus of the seminar shifted to apply these concepts to the obesity epidemic. The obesity epidemic is fueled by excess caloric intake, so the population is becoming more obese as a result of eating more calories per day compared to past years. Hedonic overeating or homeostatic dysregulation has been identified to cause obesity. This stems from the fact that there are two main types of eating: 1) Hedonic eating, or eating for pleasure, and 2) Homeostatic eating, or eating because you are hungry. Homeostatic eating rarely happens today, and it operates through a feed-forward signal to the reward system to signal you to stop eating. Hedonic eating affects the homeostatic system. Hedonic food consumption where high-calorie foods are eaten at different times of the day causes unnatural spikes and troughs in both blood sugar and hunger levels and completely messes up the ability of the homeostatic system to regulate eating.

####In the brain, homeostatic consumption is governed by a part of the hypothalamus called the arcuate nucleus. This is a population of neurons that signals for hunger and satisfaction and sends an output to the brain to tell you if you should eat or not. Hedonic food consumption is governed by the dopaminergic interaction between the part of the brain called the Ventral Tegmental Area (VTA) and its interaction with the Nucleus Accumbens (NAc).

### Dopamine Signaling and Metabolic Disorganization

####Human evolution into our modern way of living has also changed how this system operates. In the case of wild animals, it is desirable for dopaminergic neurons to become activated when eating while hungry, or when eating something that tastes good to signal the animal to take and store as much as possible. But, the reward circuit can also cause metabolic disorganization. This was studied in  DRD1 receptor knockout mice, so these mice do not have dopamine signaling ability in the area of interest. The control group used was normal, wild-type mice. The knockout and wild-type mice were put on two different diets: a high energy diet and a normal diet. Knockout animals lacking dopamine signaling ability on the high energy diet did not gain weight.

####To investigate the reason why the knockout animals did not gain weight, this same then researched the eating patterns in the wild-type versus DRD1 knockout animals. It was found that the difference between the two groups was the amount of food consumed during the day. The wild-type animals ate a normal amount of food during the night, which is the active period for nocturnal mice, but also continued to eat during the day. However, during the daytime mice are usually inactive and no not eat. So, these wild-type mice gained weight and developed obesity-related diseases such as fatty liver and diabetes. Videos recorded of the mice showed that when a wild-type mouse was placed into a cage with food during the day, it would go straight to the food and start eating. But, when the same thing was done with knockout mice during the day, they did not eat the food during the day even though it was available. During the night, both groups of mice showed the same eating behavior and immediately ate the food upon being placed in the cage.

####This is important because the study showed that DRD1 knockout mice sustained their metabolic circadian rhythms by storing food during the day and eating only at night. So, if you give a DRD1 knockout animal a high energy diet but restrict their access to it during the night, they do not gain weight. This also led into a further investigation of circadian rhythm and weight gain, which identified changing the daylight cycle of their environment as a major factor leading to weight gain. This study was similar to humans who travel across time zones and experience jet lag. The key link between jet lag and weight gain was found to be the gut microbiome of the animal. Animals that were constantly jetlagged by constantly changing their daylight exposure gained weight because of changes in their gut microbiome. However, this is not the only influencing factor. Other influencers such as gut permeability also were found to play a role in a subsequent study.

## Conclusion

####Overall, many factors play a role in weight gain and obesity, but most are linked to the physiological changes that occur in the brain and environmental factors like experiencing changes in daylight cycles. The main takeaways from this seminar are that increased DRD1-SCN signaling leads to hedonic overeating. The study with the knockout mice may imply at face value that the key to preventing obesity is eliminating DRD1 receptors. However, these receptors are crucial to maintaining important neurological function in other areas besides eating behavior. Elimination or suppression of these receptors would realistically alter the dopamine environment in the brain and lead to depression and suicide. Furthermore, what we know about obesity combined with the results of these studies suggests that obesity is in most cases self-created, but weight gain and obesity development results in changes in the brain that perpetuates the disease by making it extraordinarily difficult to return to a normal eating behavior. One environmental cause of obesity that is not truly self-created is frequently traveling between different time zones.

## Questions

####Although it was covered in this seminar that blocking DRD1 receptors, although it may prevent or reverse obesity, would also cause extremely detrimental effects to the patient such as depression and suicide. However, I am interested to know if there is any research surrounding obesity treatments that do involve a sort of brain-altering drug and if this link between DRD1-SCN and obesity could eventually help create a similar medication. Additionally, this seminar left me wondering what amount of traveling or disrupting the circadian rhythm is acceptable as to not cause detrimental health effects. Furthermore, I am interested to know if there are any other known behaviors or environmental factors that mess up the body clock that were not mentioned.